// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTG9N7QXQMzqfQ6pkrZijlDZkJKefpiP8',
    appId: '1:981083833857:web:7dd5d38d8842d154ce6200',
    messagingSenderId: '981083833857',
    projectId: 'firstfirebase-ddd8a',
    authDomain: 'firstfirebase-ddd8a.firebaseapp.com',
    storageBucket: 'firstfirebase-ddd8a.appspot.com',
    measurementId: 'G-VD9EW8ZTMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNhcQDrxP92JaFaoZDfVOHwSG-Cms7KQ',
    appId: '1:981083833857:android:087adc9a4d754cacce6200',
    messagingSenderId: '981083833857',
    projectId: 'firstfirebase-ddd8a',
    storageBucket: 'firstfirebase-ddd8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAugq7fi1rJ0-djRKlkc9JjcF3Fu1QxcTs',
    appId: '1:981083833857:ios:9e21413629300764ce6200',
    messagingSenderId: '981083833857',
    projectId: 'firstfirebase-ddd8a',
    storageBucket: 'firstfirebase-ddd8a.appspot.com',
    iosBundleId: 'com.example.firebasePost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAugq7fi1rJ0-djRKlkc9JjcF3Fu1QxcTs',
    appId: '1:981083833857:ios:9061b2e33f7fe8bcce6200',
    messagingSenderId: '981083833857',
    projectId: 'firstfirebase-ddd8a',
    storageBucket: 'firstfirebase-ddd8a.appspot.com',
    iosBundleId: 'com.example.firebasePost.RunnerTests',
  );
}
